language: java
sudo: required
addons:
  postgresql: "9.5"
services:
  - postgresql
jdk:
  - oraclejdk8
env:
  global:
    - EMBULK_INPUT_POSTGRESQL_TEST_CONFIG=`pwd`/ci/travis_postgresql.yml
cache:
  directories:  # run "travis cache --delete" to delete caches
    - $HOME/.gradle
before_script:
  - psql -c "create database travis_ci_test;" -U postgres
script:
  - ./gradlew --info check
